name: Lint

on:
  push:
    branches: [main]
    paths:
      - "**.md"
      - "**.tf"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.md"
      - "**.tf"
      - ".github/workflows/lint.yml"

env:
  TF_PLUGIN_CACHE_DIR: "$HOME/.terraform.d/plugin-cache"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: Lint markdown
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: .markdownlint.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt check
        id: fmt
        run: terraform fmt -check

      - name: Make tf-plugin-cache dir
        run: mkdir -p ${TF_PLUGIN_CACHE_DIR}

      - name: Terraform init&&validate
        run: find . -name '*.tf'  -print | xargs  dirname | uniq | time xargs -n 1 -I{}  sh -c 'terraform -chdir={} init && terraform -chdir={} validate'
